### PROJECT ###
group=com.nmcrate.key
version=1.1.0
RELEASE_URL=https://nmcrate.com/reposilite/releases
SNAPSHOT_URL=https://nmcrate.com/reposilite/snapshots
containerProjects=buildSrc,SAMPLE
### GRADLE CONFIG ###
# Enables the Gradle build cache to reuse outputs from previous builds
org.gradle.caching=true
# Configuration cache saves a copy of the project graph and reuses it
# to speed up later builds.
org.gradle.configuration-cache=true
# Parallel execution for faster builds in our multitask environment
org.gradle.parallel=true
# The Gradle daemon runs as a background process to avoid startup costs
org.gradle.daemon=true
# Optimize JVM args for Java 25/21 and Kotlin 2.3
org.gradle.jvmargs=-Xmx2g -XX:+UseParallelGC --enable-native-access=ALL-UNNAMED
# Optional but recommended for Kotlin compilation performance
kotlin.incremental=true
kotlin.caching.enabled=true
# Enables the experimental Dokka V2 runner for improved documentation generation
org.jetbrains.dokka.experimental.gradle.pluginMode=V2EnabledWithHelpers

# GDPublish Configuration
FINAL_DIR_ENABLED=false
PUBLISH_TO_PRIVATE=false
PRIVATE_USE_PUBLIC_CREDENTIALS=false
PRIVATE_URL=
